-- Add AI team fields to Team
ALTER TABLE "Team" ADD COLUMN "isAI" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Team" ADD COLUMN "aiDifficulty" TEXT NOT NULL DEFAULT 'rookie';
ALTER TABLE "Team" ADD COLUMN "aiStrategy" TEXT NOT NULL DEFAULT 'balanced';

-- Create AI Owner user
INSERT INTO "User" ("id", "email", "username", "password", "displayName", "role", "hasPaidPurchase", "createdAt", "updatedAt")
VALUES (
  'ai-system-owner-001',
  'ai@grid-game.system',
  'ai-system',
  '$2a$12$AI_SYSTEM_PASSWORD_HASH_NOT_USED_FOR_LOGIN',
  'AI System',
  'ADMIN',
  false,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("id") DO NOTHING;

-- Create AI Owner wallet
INSERT INTO "Wallet" ("id", "userId", "cash", "gridTokens", "solBalance", "createdAt", "updatedAt")
VALUES (
  gen_random_uuid(),
  'ai-system-owner-001',
  999999999,
  999999999,
  999999999,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("userId") DO NOTHING;

-- Create index for AI team lookup
CREATE INDEX "Team_isAI_idx" ON "Team"("isAI");

-- Seed initial AI teams (one per tier with varying difficulty)
-- Note: Players for these teams will be generated by the app startup seed script
INSERT INTO "Team" ("id", "name", "sportId", "ownerId", "tier", "isFree", "isAI", "aiDifficulty", "aiStrategy", "purchasePrice", "purchaseCurrency", "purchasedAt", "seasonsPlayed", "formation", "style", "pressing", "mentality", "tactics", "wins", "draws", "losses", "goalsFor", "goalsAgainst", "points", "record", "createdAt", "updatedAt")
VALUES
  -- State College AI Teams
  ('ai-team-state-001', 'Rookie High School All-Stars', 'american-football', 'ai-system-owner-001', 'STATE_COLLEGE', true, true, 'rookie', 'balanced', 0, 'FREE', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('ai-team-state-002', 'Veteran Prep Academy', 'american-football', 'ai-system-owner-001', 'STATE_COLLEGE', true, true, 'veteran', 'runHeavy', 0, 'FREE', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('ai-team-state-003', 'Elite Junior College', 'american-football', 'ai-system-owner-001', 'STATE_COLLEGE', true, true, 'elite', 'passHeavy', 0, 'FREE', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  
  -- Mid College AI Teams
  ('ai-team-mid-001', 'Rookie Community College', 'american-football', 'ai-system-owner-001', 'MID_COLLEGE', false, true, 'rookie', 'balanced', 15000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('ai-team-mid-002', 'Veteran Conference Rivals', 'american-football', 'ai-system-owner-001', 'MID_COLLEGE', false, true, 'veteran', 'aggressive', 18000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('ai-team-mid-003', 'Elite Division I Prospect', 'american-football', 'ai-system-owner-001', 'MID_COLLEGE', false, true, 'elite', 'passHeavy', 20000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  
  -- Top College AI Teams
  ('ai-team-top-001', 'Rookie FCS Program', 'american-football', 'ai-system-owner-001', 'TOP_COLLEGE', false, true, 'rookie', 'balanced', 50000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('ai-team-top-002', 'Veteran FBS Contender', 'american-football', 'ai-system-owner-001', 'TOP_COLLEGE', false, true, 'veteran', 'runHeavy', 60000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('ai-team-top-003', 'Elite Blue Blood', 'american-football', 'ai-system-owner-001', 'TOP_COLLEGE', false, true, 'elite', 'aggressive', 75000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('ai-team-top-004', 'Legend National Champion', 'american-football', 'ai-system-owner-001', 'TOP_COLLEGE', false, true, 'legend', 'conservative', 100000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  
  -- Regional Pro AI Teams
  ('ai-team-regional-001', 'Rookie Semi-Pro', 'american-football', 'ai-system-owner-001', 'REGIONAL_PRO', false, true, 'rookie', 'balanced', 200000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('ai-team-regional-002', 'Veteran Regional Champ', 'american-football', 'ai-system-owner-001', 'REGIONAL_PRO', false, true, 'veteran', 'runHeavy', 250000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('ai-team-regional-003', 'Elite Pro Prospect', 'american-football', 'ai-system-owner-001', 'REGIONAL_PRO', false, true, 'elite', 'passHeavy', 300000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  
  -- Pro Entry AI Teams
  ('ai-team-pro-001', 'Rookie Expansion Team', 'american-football', 'ai-system-owner-001', 'PRO_ENTRY', false, true, 'rookie', 'balanced', 1000000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('ai-team-pro-002', 'Veteran Playoff Contender', 'american-football', 'ai-system-owner-001', 'PRO_ENTRY', false, true, 'veteran', 'aggressive', 1200000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('ai-team-pro-003', 'Elite Franchise', 'american-football', 'ai-system-owner-001', 'PRO_ENTRY', false, true, 'elite', 'passHeavy', 1500000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('ai-team-pro-004', 'Legend Dynasty', 'american-football', 'ai-system-owner-001', 'PRO_ENTRY', false, true, 'legend', 'conservative', 2000000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  
  -- Pro Elite AI Teams (very rare, high price)
  ('ai-team-elite-001', 'Legend Super Bowl Champion', 'american-football', 'ai-system-owner-001', 'PRO_ELITE', false, true, 'legend', 'balanced', 5000000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('ai-team-elite-002', 'Legend Hall of Fame', 'american-football', 'ai-system-owner-001', 'PRO_ELITE', false, true, 'legend', 'aggressive', 7500000, 'GRID', CURRENT_TIMESTAMP, 0, '4-3-3', 'balanced', 'medium', 'balanced', '{}', 0, 0, 0, 0, 0, 0, '{}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Create venues for AI teams
INSERT INTO "Venue" ("id", "teamId", "sportId", "name", "tier", "capacity", "ticketPrice", "condition", "prestige", "createdAt", "updatedAt")
SELECT 
  gen_random_uuid(),
  t.id,
  'american-football',
  t.name || ' Stadium',
  CASE 
    WHEN t.tier = 'STATE_COLLEGE' THEN 'PARK_FIELD'
    WHEN t.tier = 'MID_COLLEGE' THEN 'COMMUNITY'
    WHEN t.tier = 'TOP_COLLEGE' THEN 'SMALL_STADIUM'
    WHEN t.tier = 'REGIONAL_PRO' THEN 'REGIONAL'
    WHEN t.tier = 'PRO_ENTRY' THEN 'PRO'
    WHEN t.tier = 'PRO_ELITE' THEN 'ELITE'
  END,
  CASE 
    WHEN t.tier = 'STATE_COLLEGE' THEN 5000
    WHEN t.tier = 'MID_COLLEGE' THEN 12000
    WHEN t.tier = 'TOP_COLLEGE' THEN 35000
    WHEN t.tier = 'REGIONAL_PRO' THEN 25000
    WHEN t.tier = 'PRO_ENTRY' THEN 65000
    WHEN t.tier = 'PRO_ELITE' THEN 100000
  END,
  15,
  80,
  CASE 
    WHEN t.tier = 'PRO_ELITE' THEN 80
    WHEN t.tier = 'PRO_ENTRY' THEN 60
    WHEN t.tier = 'REGIONAL_PRO' THEN 40
    ELSE 30
  END,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
FROM "Team" t
WHERE t."isAI" = true
ON CONFLICT DO NOTHING;

-- Join AI teams to local-rec-football league
INSERT INTO "TeamLeagueMembership" ("id", "teamId", "leagueId", "season", "status", "joinedAt")
SELECT 
  gen_random_uuid(),
  t.id,
  'local-rec-football',
  'beta',
  'ACTIVE',
  CURRENT_TIMESTAMP
FROM "Team" t
WHERE t."isAI" = true
ON CONFLICT ("teamId", "leagueId", "season") DO NOTHING;
